#!/usr/bin/env python3
"""Bounded synthesis of already documented evidence; does not download or trade."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; OUT=ROOT/'results/phase79_final_evidence_gate'
MATRIX=[
 {'requirement':'Exact fixed-contract identity for every leg/time','status':'FAIL','evidence':'Phase 75: rolling Dhan response lacks per-bar exact expiry date; expiryCode/expiryFlag cannot establish contract expiry identity.','effect':'Affected legs cannot be replayed as exact contracts.'},
 {'requirement':'Complete target-date fixed-contract observations','status':'FAIL','evidence':'Phase 76 pinned HF dataset files for 2026-07-28 and 2026-08-04 contain trades only through 2026-07-02; expiry sessions absent.','effect':'Those expiry dates remain excluded; no imputation.'},
 {'requirement':'Automated-use and retention rights verified for complete sample','status':'UNVERIFIED','evidence':'Prior source gates did not accept a source satisfying all sample, rights and target-coverage requirements. HF dataset card indicates CC-BY-NC-4.0, which is not accepted here as a general commercial-use clearance.','effect':'No bulk raw-data caching/publication without documented terms.'},
 {'requirement':'Cost-aware reproducible accounting','status':'PARTIAL','evidence':'Phase 51-3/50B frozen engine outputs include Paytm Money cost scenarios and friction stresses; Phase 77 ledger reconciliation passed. OHLC-based outcomes are not quote/depth-executable fills.','effect':'Model accounting is reproducible but fill realism remains limited.'},
 {'requirement':'Temporal/out-of-sample stability','status':'FAIL','evidence':'Phase 78: TT-04 historical HOLD base -₹6,456.29 and +50% friction -₹11,148.57; TT-05 HOLD base -₹40,244.68 and ₹20/order +50% friction -₹49,605.30, despite positive short partial-window outcomes.','effect':'No strategy promotion.'},
 {'requirement':'Reproducible audit trail','status':'PASS','evidence':'Phase 71–78 branches record plans/status/error logs and completed workflow evidence; Phase 77 ledger reconciliation had no count/net errors.','effect':'Sufficient to document the research no-go, not to claim profitability.'}
]
def main():
 failed=[x for x in MATRIX if x['status'] in ('FAIL','UNVERIFIED')]
 decision='NO_GO_INSUFFICIENT_EVIDENCE' if failed else 'ELIGIBLE_FOR_REVIEW_NOT_AUTOMATIC_PROMOTION'
 out={'phase':79,'decision':decision,'scope':'Synthesis of existing audited evidence only; no new data retrieval or trading simulation.','evidence_matrix':MATRIX,'strategies':{'TT-02':'Not supported in the available partial sample; negative in all four registered cost/friction cases.','TT-04':'Not promoted; partial-window gains conflict with negative historical HOLD; bootstrap intervals include zero.','TT-05':'Not promoted; partial-window gains conflict with negative historical HOLD; bootstrap intervals include zero.'},'excluded_expiries':['2026-07-28','2026-08-04'],'reopen_only_if':['A concrete source provides exact expiry/strike/side identity and complete target-date bars.','Documented license/API terms permit intended automated analysis and retention.','Quote/spread or defensible conservative execution assumptions and Paytm Money charges can be applied.','A pre-registered temporal test can be run without reusing the same holdout for tuning.'],'not_claimed':['This is not proof that all strategies are unprofitable.','No strategy is approved for live trading.','The result does not replace the final research manuscript; it defines the evidence boundary and stop decision.']}
 OUT.mkdir(parents=True,exist_ok=True); (OUT/'summary.json').write_text(json.dumps(out,indent=2)+'\n')
 lines=['# Phase 79 — Final evidence sufficiency decision','',f'**Decision: {decision}**','','## Evidence matrix','','| Requirement | Status | Evidence / implication |','|---|---|---|']
 for x in MATRIX: lines.append(f"| {x['requirement']} | **{x['status']}** | {x['evidence']} {x['effect']} |")
 lines += ['', '## Strategy disposition','','- **TT-02:** not supported; negative in all four registered cost/friction cases in the available partial sample.','- **TT-04:** not promoted. Positive partial-window results conflict with a negative historical HOLD split; cluster-bootstrap intervals include zero.','- **TT-05:** not promoted. Positive partial-window results conflict with a strongly negative historical HOLD split; cluster-bootstrap intervals include zero.','', '## Data exclusions','','Expiries 2026-07-28 and 2026-08-04 remain explicitly excluded. The HF target-named files do not contain the expiry-session bars. Rolling Dhan history is not accepted as fixed-expiry identity. No missing prices were synthesized.','', '## Conclusion','','The evidence is insufficient to recommend a strategy. This is a **research no-go**, not a claim that every conceivable strategy is unprofitable. The finite empirical promotion path stops here until a genuinely new, authorized and contract-identifiable sample is available. Broad source-search loops and outcome-driven parameter changes are not justified.','', '## Conditions to reopen','']
 lines += [f'- {x}' for x in out['reopen_only_if']]
 lines += ['', '## Limitations and next research','','The existing outputs are based on minute OHLC, not historical bid/ask/depth; conservative friction stress does not establish real fillability. Any future study must retain Paytm Money brokerage and all applicable statutory charges, date-aware lot sizes, adverse slippage and spread costs. If reopened, begin with rights/sample validation, then a frozen rule-faithful replay, temporal stability, independent holdout, and manuscript generation. No strategy is approved for live trading.']
 (OUT/'report.md').write_text('\n'.join(lines)+'\n'); print(json.dumps({'decision':decision,'failed_or_unverified':len(failed),'matrix_rows':len(MATRIX)},indent=2))
if __name__=='__main__': main()
